Repository leven-cn/python-weblint, pull requests merged in 2018-07, with the labels that each got.

#1 First commit on HTML rules
  README.md
Labels: good first issue

#2 Minor fix
  README.md
Labels: bug

#3 Create html files for E01001-E01013 testcase
  tests/E01001.html
  tests/E01002.html
  tests/E01003.html
  tests/E01004.html
  tests/E01005.html
  tests/E01006.html
  tests/E01007.html
  tests/E01008.html
  tests/E01009.html
  tests/E01010.html
  tests/E01011.html
  tests/E01012.html
  tests/E01013.html
Labels: question

#6 Add unittest script
  test.sh
  tests/__init__.py
Labels: good first issue

#7 为E01001规则添加示例
  Rule.md
Labels: enhancement

#8 为E01002-E01013规则添加示例
  README.md
  Rule.md
Labels: enhancement

#10 Support E01001-E01013
  weblint/__init__.py
  weblint/weblint.py
Labels: enhancement

#11 Improve E01005
  Rule.md
  weblint/weblint.py
Labels: enhancement

#13 Add English comments for HTML Rule
  Rule.md
Labels: enhancement

#14 Support HS0001-HS0004
  README.md
  Rule.md
  tests/E01013.html
  tests/HS0001.html
  tests/HS0002.html
  tests/HS0003.html
  tests/HS0004.html
  tests/test_weblint.py
  weblint/weblint.py
Labels: enhancement

#16 Support HS0015-HS0034, and HA0001
  README.md
  Rule.md
  tests/E.html
  tests/E01008.html
  tests/HA0001.html
  tests/HS0015.html
  tests/HS0016.html
  tests/HS0017.html
  tests/HS0018.html
  tests/HS0019.html
  tests/HS0020.html
  tests/HS0021.html
  tests/HS0022.html
  tests/HS0023.html
  tests/HS0024.html
  tests/HS0025.html
  tests/HS0026.html
  tests/HS0027.html
  tests/HS0028.html
  tests/HS0029.html
  tests/HS0030.html
  tests/HS0031.html
  tests/HS0032.html
  tests/HS0033.html
  tests/HS0034.html
  tests/test_weblint.py
  weblint/weblint.py
Labels: enhancement

#18 minor fix
  README.md
Labels: bug

#19 Add "frameset" and "noframes" into deprecated elements
  Rule_HTML.md
  weblint/weblint.py
Labels: bug

#21 Create CSS rules, according to CSSLint
  README.md
  Rule_CSS.md
Labels: enhancement
